# Generated by Django 4.1 on 2023-02-23 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('course_code', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('creatorid', models.CharField(max_length=20)),
                ('classes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('attendance_data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('department_code', models.CharField(max_length=20)),
                ('rep_code', models.CharField(max_length=255)),
                ('timetable', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=20)),
                ('creatorid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('has_deadline', models.CharField(max_length=2)),
                ('deadline_text', models.CharField(max_length=20)),
                ('deadline_digit', models.CharField(max_length=20)),
                ('imageset', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=20)),
                ('class_code', models.CharField(default='nil', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=20)),
                ('matric', models.CharField(default='non_student', max_length=20)),
                ('accept_status', models.CharField(default=0, max_length=20)),
                ('cashbalance', models.FloatField(default=0)),
            ],
        ),
    ]
