# Generated by Django 4.1 on 2023-02-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='mClass',
        ),
    ]
