# Generated by Django 4.1 on 2023-03-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_face',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
