# Generated by Django 4.1 on 2023-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cashbalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric',
            field=models.CharField(default='non_student', max_length=20),
        ),
    ]
