# Generated by Django 4.1 on 2023-01-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_cashbalance_alter_user_matric'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='jsdns', max_length=255),
            preserve_default=False,
        ),
    ]
