# Generated by Django 4.1 on 2023-02-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_class_mclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mClass',
            new_name='Class',
        ),
    ]
