# Generated by Django 4.1 on 2023-02-28 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_mclass_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=20)),
                ('callback_url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('owners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('otherdata', models.JSONField(null=True)),
            ],
        ),
    ]
