# Generated by Django 4.1 on 2023-03-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
